### ISSUE TITLE
Corrupted .sch file?

### ISSUE THREAD

**Issue by ferventgeek** [adafruit/Adafruit-16-Channel-PWM-Servo-Driver-PCB#1]
It looks like the .sch file has a couple corrupted lines, (first one at 65), with binary chars being wonky-converted to ASCII inline.  Any chance there's an original version of this file?  Thx!

**Comment by ladyada** [comment]
just checked, opens fine - its the only file we've got :)

**Comment by ferventgeek** [comment]
And.. <testing>.. of course it works on Win10. It's a My Mac Thing then. Thx for testing :)
